### ISSUE TITLE
非常有意思的对比

### ISSUE THREAD

**Issue by serco-chen** [songjiayang/crystal-vs-golang#1]
不太了解go，试下GOMAXPROCS=1再比较一下试试。

目前crystal背后的fiber还是单线程，这样比较结果比较有价值一点。
感觉crystal距离 production ready 已经开始接近了。

**Comment by songjiayang** [comment]
因为官方给的这个例子，所以对照写了一个 golang 版本

1. 发现 golang 有作弊嫌疑， 因为 golang 统计文件行数的那段代码本身执行速度大约是 crystal 的两倍，但是 crystal 代码可读性强太多了。

2. 一开始我测试的时候， crystal 没有使用 --release 参数。

因为例子中基本都是 IO 操作，CPU 不是瓶颈，猜测设置 GOMAXPROCS=1 影响不大，我想核心问题还是上面 2 点。

不过作为对比，确实设置 GOMAXPROCS=1 更合理。

@serco-chen

**Comment by songjiayang** [comment]
设置 `GOMAXPROCS=1` 后反而变快了，数据大致为：

```
real	0m16.709s
user	0m9.389s
sys	0m7.807s
finish countfilelines-crystal test

real	0m8.700s
user	0m2.393s
sys	0m4.931s
finish countfilelines-go test
```

**Comment by serco-chen** [comment]
@songjiayang 两边都disable gc再比较看看
```
发现 golang 有作弊嫌疑， 因为 golang 统计文件行数的那段代码本身执行速度大约是 crystal 的两倍，但是 crystal 代码可读性强太多了。
```
这个是什么意思？为什么有作弊嫌疑的，没发现有什么问题啊。

**Comment by songjiayang** [comment]
我意思是这个例子主要目的是并发能力比较，但是单个并发内部函数执行时间有差距，golang 读取单个文件速度快比 crystal 快一倍左右。

**Comment by serco-chen** [comment]
@songjiayang 那目前没有对比的价值，crystal并发模型还没有完全确定下来，目前的实现应该只是过渡时期用的。

**Comment by songjiayang** [comment]
@serco-chen  不过从语法上看，蛮不错的
